[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
# Configuration Values to Ensure Yul is inlined nicely, and optimized well
optimizer = true
optimizer_runs = 2000
via_ir = true
# Configuration to ensure strict fuzzing testing
fuzz_runs = 500

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true

[etherscan]
mainnet = { key = "${ETHERSCAN_API}" }

[rpc_endpoints]
mainnet = ""
optimism = ""
arbitrum = ""
polygon = ""

[fmt]
line_length = 160
bracket_spacing = true
number_underscore = "thousands"
wrap_comments = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
ignore = ["libs/*","*.t.sol"]
